### ISSUE TITLE
Android devices: Error: browserType.launch: Browser has been closed

### ISSUE THREAD

**Issue by vitali-hanich** [browserstack/node-js-playwright-browserstack#11]
When I am trying to run the `sample-test` script with an Android device, I am getting the error:
`Error: browserType.launch: Browser has been closed`.
For Windows it works perfectly fine.

Steps to reproduce:
``` 
git clone https://github.com/browserstack/node-js-playwright-browserstack.git
```
Checkout to `sdk` branch.

Update the configuration file.
*browserstack.yml*
```yml
platforms:
  - deviceName: Samsung Galaxy S22 Ultra
    browserName: chrome # Try 'samsung' for Samsung browser
    osVersion: 12.0
```

*package.json*
``` json
"devDependencies": {
    "@playwright/test": "^1.35.0",
    "browserstack-node-sdk": "latest"
  }
```
